### PR TITLE
add discord timestamp support in handleView

### PR DESCRIPTION
**Pull request by helloimalastair**
# Pull Request

## Description

Adding Discord Timestamp support for `handleView`, allowing real-time updating timestamps.

## Documentation

For _any_ version updates, please verify if the [documentation page](https://docs.beccalyria.com?utm_source=github&utm_medium=pr-template) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.

- [x] My contribution does NOT require a documentation update.
- [ ] My contribution DOES require a documentation update.

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
I like this - let's implement this.

**Comment by helloimalastair** [comment]
@naomi-lgbt All checks passed(except the `sleep` function. Is that something I need to fix? Other than that, should be ready for merge,

**Comment by naomi-lgbt** [comment]
Yeah that's just a flaky test.

**Review by naomi-lgbt — APPROVED** [review]
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Comment by naomi-lgbt** [comment]
## Thank You

Thank you for your continued contribution to our project. We have reviewed your pull request and are happy to accept these changes.

Please continue to watch for issues labelled `help wanted`, as these will be additional opportunities to contribute.

You can also see all open issues [through our contributor tool](https://contribute.nhcarrigan.com)

**Pull request merged**
