### PR TITLE
Update PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by adarsh500**
# Pull Request

## Description:

Updates the link in PR template from https://beccalyria.nhcarrigan.com to https://www.beccalyria.com/discord-documentation

## Related Issue:

Closes BeccaLyria#626

## Documentation:

For _any_ version updates, please verify if the [documentation page](https://beccalyria.nhcarrigan.com) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.

- [ ] My contribution DOES require a documentation update.

### CODE REVIEW

**Review by nhcarrigan — APPROVED** [review]
Looks good to me.

**Review by adityaraute — APPROVED** [review]
Works

**Comment by nhcarrigan** [comment]
Approved yesterday but forgot to click the merge button oops!

**Comment by nhcarrigan** [comment]
## Congratulations

Congratulations on making your first pull request to our project. We have reviewed your contributions and are happy to accept them.

We hope you enjoyed the contribution process, and encourage you to watch for issues labelled `help wanted` for additional opportunities to contribute.

**Pull request merged**
