### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by numanjvd82**
# Pull Request

## Description:

Add a link to the bot documentation in the first section

## Documentation:

For _any_ version updates, please verify if the [documentation page](https://beccalyria.nhcarrigan.com) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.

- [ ] My contribution does NOT require a documentation update.

### CODE REVIEW

**Review by nhcarrigan — CHANGES_REQUESTED** [review]
Let's move it up above the badges, so it's with the text on line 5. I think we should also make it a markdown link.

Something like:

```md
[You can invite Becca to your own server!](http://invite.beccalyria.com) Already have her there? [Read the documentation](https://www.beccalyria.com/discord-documentation) to get her set up!
```

**Comment by numanjvd82** [comment]
Right I'll do that

**Review by nhcarrigan — APPROVED** [review]
Looks good to me!

**Comment by nhcarrigan** [comment]
## Congratulations

Congratulations on making your first pull request to our project. We have reviewed your contributions and are happy to accept them.

We hope you enjoyed the contribution process, and encourage you to watch for issues labelled `help wanted` for additional opportunities to contribute.

**Pull request merged**
