### PR TITLE
fix: Removed the UP! reaction for messages

### LINKED ISSUE #666: [OTHER] Remove The "UP!" reaction after gaining the experince points.
Ref: Conversation in the community 

Goals
- Remove the feature of reacting to the message which has generated experience for leveling.

### PR DESCRIPTION
**Pull request by kaiwalyakoparkar**
# Pull Request

## Description:
This PR will remove the "UP!" (:up:) reaction of the bot to the messages which have fetched the experience points to the user.

## Related Issue:

Closes #666

## Scope:

Did you remember to update the `package.json` version number?

- [ ] Major Version Update: X.\_.\_ (for complete code refactors, or large PRs that adjust most of the codebase)
- [ ] Minor Version Update: \_.X.\_ (for the addition of new commands)
- [x] Patch Version Update: \_.\_.X (for bug fixes _in the code_.)
- [ ] No Version Update: \_.\_.\_ (no version update for additions to tests, documentation, or anything that isn't end-user facing.)

## Documentation:

For _any_ version updates, please verify if the [documentation page](https://www.beccalyria.com/discord-documentation) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.

- [ ] My contribution does NOT require a documentation update.
- [x] My contribution DOES require a documentation update.

### CODE REVIEW

**Comment by nhcarrigan** [comment]
As this is a change in functionality, it should include a version update. For this change, I'd do a patch version.

You can do this by running `npm version patch` locally - this will automatically generate a commit with the version bump. Push that up to your branch and the PR will update automatically.

**Comment by nhcarrigan** [comment]
It also does require a documentation update, since the `UP` reaction is mentioned there.

**Comment by kaiwalyakoparkar** [comment]
Thanks for reviewing @nhcarrigan I will make the changes respectively

**Comment by kaiwalyakoparkar** [comment]
@nhcarrigan I have done changes as you asked. Lemme know if any edits need to be done

**Review by nhcarrigan — APPROVED** [review]
Looks good to me!

**Comment by nhcarrigan** [comment]
## Congratulations

Congratulations on making your first pull request to our project. We have reviewed your contributions and are happy to accept them.

We hope you enjoyed the contribution process, and encourage you to watch for issues labelled `help wanted` for additional opportunities to contribute.

**Pull request merged**
