### PR TITLE
Feat/currency reminder

### LINKED ISSUE #1137: [FEAT] - Currency Notification/Reminder
### What feature would you like to see?

Reminds user when they can claim Currency. (like the karuta bot)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Vyvy-vi**
# Pull Request

## Description

This PR adds daily/weekly reminders sent to the server via a webhook.
New crowdin data-
`commands:currency.daily.reminder` and `commands:currency.weekly.reminder`

Q) What can be improved here?

## Related Issue

Closes #1137 

## Documentation

For _any_ version updates, please verify if the [documentation page](https://www.beccalyria.com/discord-documentation) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.

- [ ] My contribution does NOT require a documentation update.
- [x] My contribution DOES require a documentation update.

### CODE REVIEW

**Comment by Vyvy-vi** [comment]
Q) Would it be desirable to make `CURRENCY_REMINDER_WH` an optional variable and make it default to the `CURRENCY_WH`?

**Comment by nhcarrigan** [comment]
Nope. The currency webhook is the debug hook that pipes to a private channel.

**Review by nhcarrigan — APPROVED** [review]
Let's go ahead and get this in.

**Comment by nhcarrigan** [comment]
## Thank You

Thank you for your continued contribution to our project. We have reviewed your pull request and are happy to accept these changes.

Please continue to watch for issues labelled `help wanted`, as these will be additional opportunities to contribute.

**Pull request merged**
