### PR TITLE
fix: block fb links (#985)

### LINKED ISSUE #985: [BUG] - block Facebook short links
### What bug did you encounter?

`.watch` link did not get removed

### What did you expect to happen?

`.watch` link to be removed

### Screenshots

Screenshot 2021-11-28 at 07 11 16

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by eddiejaoude**
# Pull Request

## Related Issue

Closes #985 

## Documentation

For _any_ version updates, please verify if the [documentation page](https://www.beccalyria.com/discord-documentation) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.

- [x] My contribution does NOT require a documentation update.
- [ ] My contribution DOES require a documentation update.

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Hmmm 🤔 

Screenshot 2021-11-28 at 07 24 29

**Comment by nhcarrigan** [comment]
Yeah that one gets a little aggressive sometimes.

**Review by nhcarrigan — APPROVED** [review]
Looks good to me.

**Comment by nhcarrigan** [comment]
## Thank You

Thank you for your continued contribution to our project. We have reviewed your pull request and are happy to accept these changes.

Please continue to watch for issues labelled `help wanted`, as these will be additional opportunities to contribute.

**Pull request merged**
