### PR TITLE
bug/fix-heptagram-api-issues

### PR DESCRIPTION
**Pull request by j-dogcoder**
# Pull Request

## Description
Fixes some endpoint issues related to the Heptagram API!

## Documentation

For _any_ version updates, please verify if the [documentation page](https://docs.beccalyria.com?utm_source=github&utm_medium=pr-template) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.

- [x] My contribution does NOT require a documentation update.
- [ ] My contribution DOES require a documentation update.

### CODE REVIEW

**Comment by j-dogcoder** [comment]
Hey @nhcarrigan, hoping we can merge this before you deploy on Sunday...

**Review by nhcarrigan — APPROVED** [review]
I'm hoping the response structure didn't change.

**Comment by j-dogcoder** [comment]
> I'm hoping the response structure didn't change.

Nope, all set there!

**Comment by j-dogcoder** [comment]
Let me know when this deploys @nhcarrigan!

**Pull request merged**
